---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test001-apiserver
  namespace: default
  labels:
    api: test001
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: test001
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: test001
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: kin-agg:0.8
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: test001
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: test001
  namespace: default
  labels:
    api: test001
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lJTEp3WE5JTDkxUDB3RFFZSktvWklodmNOQVFFTEJRQXdaekVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURW1NQ1FHQTFVRUF3d2RkR1Z6ZERBd01TMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3CkhoY05Nak13TVRFM01UVTBNalEyV2hjTk16TXdNVEUwTVRVME1qUTJXakFlTVJ3d0dnWURWUVFERXhOMFpYTjAKTURBeExtUmxabUYxYkhRdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQQp6NEpDZDRSR3cyMzBJN3RYZFhZd2lIZkNwOXFDcVFSZUM1TUpDZVNTRFZHamh1by9IaXJjR0RNSFlhaDNoY0xYCm5rRlhTK3QzK1NZQk1WVW9OMmZSS3FuS3EwWWRPTlIzOXUvY1ZqWHRYQ2xJcnM0WEV6azVaRnBISGFNUmp4dHUKYUFzbmNXVDJmc3FyM2txYVhDekdtL3NLY3V1bUhpWXg5VkNMOFkyeXh2bzRrWG1qMTZLeWdGZ3A0d1hWMnNCKwpRSmVKTnMrWThGRVNhSUNPUlZVV3B6Mkdid2xJTVNIZGNkZUdLRTVsTEdFR2tveEdBQUFmV0NMblBTeWxIRnowCmpLQ2c3VDIrZW54Szh4R214TlQ5ZHVHckhKdlNRbUV1ZG5Rd3F1MFc5Wm9GbXV4ZWVyeFcwRkNsR2dmZzVvM00KWXh0akhwT1JxZDRoZ1ZSMERDMkVLd0lEQVFBQm80R0VNSUdCTUE0R0ExVWREd0VCL3dRRUF3SUZvREFkQmdOVgpIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdId1lEVlIwakJCZ3dGb0FVc1ppYUhKYjhDSVVwClJxV095NWFyOWJFWXBYb3dMd1lEVlIwUkJDZ3dKb0lKYkc5allXeG9iM04wZ2hOMFpYTjBNREF4TG1SbFptRjEKYkhRdWMzWmpod1IvQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREJwdG5TZ29kZFRJSGxqT0lzbThjUwpHdmUxeDM1bTgvbXRscFBMTVk1WWc0NUg0R0R4SS9zbDZKQXNOWE9iZlBrVE1MZ0hTbGEyRDdVYXppS0xBaEI0ClZRQ09SQTN3YzFXam1BbGkxSDJZRHloYzdwMWR2a0V3b0lqaUMrK29vSTFkanV5NXJoK1BUb0JBWWdUVjZQQ1AKRTFkaWtCanh6cDRnNWhUQXpQZmpaU0VQQ2VzYkFNU0RPekJEQTlhNXdJcTdhWUUyRW5aOUV0eVU5a2tMampvSQpqR3RERHZWZm92dlpjM0pnVHkvZmFkV0JuSmdUMFEraFRmVTBjYnNJTTVHVi9kazUxM00rT1lpRlVGUkpsa1JGCkpTdmVldFJteHRYVGwwRC9qOVhsenIyaTlwWGN5dWZiM2ZpMUtHNFAvM1ZlSDJwOVBWL1k0Z2UyMWtqTStEaVQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBejRKQ2Q0Ukd3MjMwSTd0WGRYWXdpSGZDcDlxQ3FRUmVDNU1KQ2VTU0RWR2podW8vCkhpcmNHRE1IWWFoM2hjTFhua0ZYUyt0MytTWUJNVlVvTjJmUktxbktxMFlkT05SMzl1L2NWalh0WENsSXJzNFgKRXprNVpGcEhIYU1Sanh0dWFBc25jV1QyZnNxcjNrcWFYQ3pHbS9zS2N1dW1IaVl4OVZDTDhZMnl4dm80a1htagoxNkt5Z0ZncDR3WFYyc0IrUUplSk5zK1k4RkVTYUlDT1JWVVdwejJHYndsSU1TSGRjZGVHS0U1bExHRUdrb3hHCkFBQWZXQ0xuUFN5bEhGejBqS0NnN1QyK2VueEs4eEdteE5UOWR1R3JISnZTUW1FdWRuUXdxdTBXOVpvRm11eGUKZXJ4VzBGQ2xHZ2ZnNW8zTVl4dGpIcE9ScWQ0aGdWUjBEQzJFS3dJREFRQUJBb0lCQURMWnZPZ0U1a0psNDNvTwpJclNLTGdLRE5wUmptN2xIZExScFo4R2czWm1kOC9EUDNuL0tDUDExSTgzdXRydDByOW44TVNSTm82ek9mMlJUCmRmTjk0V2dQQzdkRkMwd3Q1T2dDaDRBbzN1M0N3Q2oySC9sNkFISnpIUkpLTDdkZUJZUkJsM3pXUFFGOU1QamMKVjA5WE9hUm50SHZNKzN4UDU5WXgwdGx5MitpZVg1bU4zOWE3cTd4M0dBSkYwYlVyZy9ndm50RHFYbER3ajhBNwpKK3NHYWRJUGJyd0FBZ0ZraFpVSm9NSnhDVG9nYzNqZkdtbGJCdUVCV2FENjlZK0dOZ3lINHN4UXVZMEhuYWxvCjFGYkh4TDVqODl0MWdHY2JJUlNtT0xoWHpnTG5oR0FteWVsY1ZhUURjNUdYaG5sQ2tVSWNTcDVSK2xwOTZ4L3IKU2pHQTZLRUNnWUVBMXZHTC83OWFLaG4rWEhWN2ZERjI1aHI4aC9qQXo3cit0cUtGSkI3ZmxvanRPN0F6Yy8rTQpxSWg0MEM3aE5ScUd1QTFhcVU5K2pHM2piMGIxV3Q0YWYyZDBFOUtKWVA5SVo5Q0ozQnhjQXQxYlNWaUZrUVQrClV2TElmU1ROdUZOQU9uaG9CSE03dzJTSmlnTTNDaktQcnVaV0d5NUtlODFmVk5rZnM4WlNITlVDZ1lFQTl5VXEKUVdJZ1V2ZE1Sdy9ZdG5NU08xRFhoNlJQdFBGL2ZYMkEzU1BmRXpVT2FnK2o3NWFxMW9WSEo0Z0g4TlVQMXlPSQo2WU9ZZGRic3VvNEZjOGFWZzFIM2s1ck95OUxLbzR5R2JMNllqRktjbVQ5UXFYcXE5OVBrbmkvWWZtaGVKQVhXCmdhK3E3ZFFTdTU5WG9OQUg1T3V3bkdGUzlTVDhzNUhaN0FBTm5QOENnWUVBbld4MXE4NzYrNERrTWRWOXBuMFgKNXZuMjRLTkluQndKdDd1YUpkVlN6bzdrcVdXb21abWQ3RVZmcnFIWElheVc1TEFyS1h2bVpIV0xNSkhZMno5MgpTcjk3WFpWQ05yOWh5VjhMeVNFZ0pwejI0ZVlxbFFjQ09jQkZKSnJTN09CVVZ6NmVlRHZwbG5iSTRVTHZpZEYwCk9KWE1sTVczbWFyVjJtL1hielNlS1MwQ2dZRUFnSlFsVjc3bGNrU1d1cUhUN1pnUWRDdXE5amJXQVIxalpyWlUKeExoVTVubEQ5b29Na0NtaTE5aWZIRUg1WDZKNWkwUkJocnVnSmk2YkdyT293b01lWmlQTzJreEFLbXFRWW1aSgp5V21maytHbTkxT3BjNE1PVDhFOXY4N0VvMzlJK3hUT2RNb2Y4M3ZTQXlyelBBYi9GR3BLaUJGYVI0L21xTVhJCnlxOThaYUVDZ1lBRUtpM2QvMFFldkRWWFJaanFjb0JjYm1ld0FNZ0dkdXhGVmVkZFBQWXUwaDZ0UTRrT096RkUKbEcwRTB3OFM1c2FleGlxbC8wUFpUQnEyRDlpZjlwMDdvWVVralA5OFVZZENHWTZ1THovZStzeWxhVkFjalJrMQp2WDVaWmlIZ0JMVTM4OUVGK1dadUx4cTRQQ25JN3pqQ1RYT3hsaDhKQnZ0WWExRUhMYXhCdnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: test001
  namespace: default
  labels:
    api: test001
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: test001
    apiserver: "true"
