---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test001-controller
  namespace: default
  labels:
    api: test001
    controller: "true"
spec:
  selector:
    matchLabels:
      api: test001
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: test001
        controller: "true"
    spec:
      containers:
      - name: controller
        image: kin-agg:0.8
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: test001
